"""
plot.py - Plotly visualization functions for LinDistModel results
"""

from typing import Optional
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from distopf.matrix_models.base import LinDistBase
from distopf.api import Case
from distopf.results import PowerFlowResult


def _get_id_name_cols(df: pd.DataFrame) -> tuple[str, str]:
    """Return the (id_col, name_col) pair present in df.

    Supports both bus-indexed DataFrames (id, name) and
    branch-indexed DataFrames (tb, to_name).
    """
    if "tb" in df.columns:
        return "tb", "to_name" if "to_name" in df.columns else "tb"
    return "id", "name"


def _choose_t(df, t=None):
    df = df.copy()
    if "t" in df.columns:
        if t is None and len(df) > 0:
            t = min(df.t)
        df = df.loc[df.t == t, :]
        df = df.drop("t", axis=1)
    return df


def _remove_empty_triplex_phases(df: pd.DataFrame) -> pd.DataFrame:
    """Remove s1 and s2 columns if they contain only NaNs or 0s.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame to clean

    Returns
    -------
    pd.DataFrame
        DataFrame with empty triplex columns removed
    """
    df = df.copy()
    for col in ["s1", "s2"]:
        if col in df.columns:
            col_data = df[col].dropna()
            if len(col_data) == 0 or (col_data == 0).all():
                df = df.drop(columns=[col])
    return df


def plot_schedules(schedules: pd.DataFrame) -> go.Figure:
    """
    Plot time-series schedules as faceted line plots.

    Each column (except 'time') is plotted as a separate facet row with
    its own independent y-axis scale. Variables are differentiated by color
    with y-axis titles showing the variable name.

    Parameters
    ----------
    schedules : pd.DataFrame
        DataFrame with a 'time' column and arbitrary number of schedule columns

    Returns
    -------
    fig : Plotly figure object
        Faceted line plot with one row per schedule variable
    """
    df = schedules.copy()
    variables = [col for col in df.columns if col != "time"]

    df_melted = df.melt(id_vars="time")

    fig = px.line(
        df_melted, x="time", y="value", facet_row="variable", color="variable"
    )

    # Hide legend and remove facet annotations
    fig.update_layout(showlegend=False)
    fig.for_each_annotation(lambda a: a.update(text=""))

    # Make y-axes independent and set titles
    # Reverse the order to match facet row ordering
    for i, variable in enumerate(reversed(variables), 1):
        fig.update_yaxes(title_text=variable, matches=None, row=i, col=1)

    return fig


def plot_voltages(v: pd.DataFrame, t=None) -> go.Figure:
    """
    Parameters
    ----------
    v : pd.DataFrame, Dataframe containing solved voltages for each bus.
        Typically generated by the LinDistModel.get_voltages() method.
    t : int or None
        Time step to plot. If None and v contains multiple time steps,
        creates an animated figure with a slider.

    Returns
    -------
    fig : Plotly figure object
        Plotly figure object containing the voltage magnitudes for each bus.
        If multiple time steps are present and t is None, returns an animated figure.
    """
    v = _remove_empty_triplex_phases(v)

    v = v.copy()
    if "id" not in v.columns:
        v["id"] = v.index
    if "name" not in v.columns:
        v["name"] = v["id"]

    # Check if we should create animation
    animate = t is None and "t" in v.columns and len(v.t.unique()) > 1

    if not animate:
        v = _choose_t(v, t=t)
        v = v.melt(
            ignore_index=False, id_vars=["id", "name"], var_name="phase", value_name="v"
        )
        v["v"] = v["v"].astype(float)
        fig = px.scatter(v, x=v.name, y="v", facet_col="phase", color="phase")
    else:
        v = v.melt(
            ignore_index=False,
            id_vars=["id", "name", "t"],
            var_name="phase",
            value_name="v",
        )
        v["v"] = v["v"].astype(float)
        fig = px.scatter(
            v, x=v.name, y="v", facet_col="phase", color="phase", animation_frame="t"
        )

    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
    fig.for_each_xaxis(lambda a: a.update(title="Bus Name"))
    return fig


def compare_voltages(v1: pd.DataFrame, v2: pd.DataFrame, t=None) -> go.Figure:
    """
    Visually compare voltages by plotting two different results.
    Parameters
    ----------
    v1 : pd.DataFrame
    v2 : pd.DataFrame

    Returns
    -------
    fig : Plotly figure object
    """
    v1 = _remove_empty_triplex_phases(v1)
    v2 = _remove_empty_triplex_phases(v2)
    v1 = v1.copy()
    v2 = v2.copy()
    if "id" not in v1.columns:
        v1["id"] = v1.index
    if "name" not in v1.columns:
        v1["name"] = v1["id"]
    if "id" not in v2.columns:
        v2["id"] = v2.index
    if "name" not in v2.columns:
        v2["name"] = v2["id"]
    t1 = t2 = t
    if t is None and "t" in v1.columns:
        t1 = min(v1.t)
    if t is None and "t" in v2.columns:
        t2 = min(v2.t)
    if "t" in v1.columns and "t" in v2.columns:
        assert t1 == t2
    if "t" in v1.columns:
        v1 = pd.DataFrame(v1.loc[v1.t == t1, :])
        v1 = v1.drop("t", axis=1)
    if "t" in v2.columns:
        v2 = pd.DataFrame(v2.loc[v2.t == t2, :])
        v2 = v2.drop("t", axis=1)
    v1 = v1.melt(
        ignore_index=True, var_name="phase", id_vars=["id", "name"], value_name="v1"
    )
    v2 = v2.melt(
        ignore_index=True, var_name="phase", id_vars=["id", "name"], value_name="v2"
    )
    v = pd.merge(v1, v2, on=["id", "name", "phase"])
    v = v.melt(
        ignore_index=True,
        var_name="value",
        id_vars=["id", "name", "phase"],
        value_name="v",
    ).sort_values(by=["id", "phase"])
    # v1["v1"] = v1["v1"].astype(float)
    # v2["v2"] = v2["v2"].astype(float)
    # v = pd.merge(v1, v2, on=["name", "phase"])
    fig = px.line(v, x="name", facet_col="phase", y="v", color="value", markers=True)
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
    fig.for_each_xaxis(lambda a: a.update(title="Bus Name"))
    return fig


def voltage_differences(v1: pd.DataFrame, v2: pd.DataFrame, t=None) -> go.Figure:
    """
    Visually compare voltages from two different results by plotting the difference v1-v2.
    Parameters
    ----------
    v1 : pd.DataFrame
    v2 : pd.DataFrame

    Returns
    -------
    fig : Plotly figure object
    """
    v1 = _remove_empty_triplex_phases(v1)
    v2 = _remove_empty_triplex_phases(v2)
    v1 = v1.copy()
    v2 = v2.copy()
    if "id" not in v1.columns:
        v1["id"] = v1.index
    if "name" not in v1.columns:
        v1["name"] = v1["id"]
    if "id" not in v2.columns:
        v2["id"] = v2.index
    if "name" not in v2.columns:
        v2["name"] = v2["id"]
    if "t" in v1.columns:
        if t is None:
            t1 = min(v1.t)
        v1 = pd.DataFrame(v1.loc[v1.t == t1, :])
        v1 = v1.drop("t", axis=1)
    if "t" in v2.columns:
        if t is None:
            t2 = min(v2.t)
        v2 = pd.DataFrame(v2.loc[v2.t == t2, :])
        v2 = v2.drop("t", axis=1)
    v1 = v1.melt(
        ignore_index=True, var_name="phase", id_vars=["id", "name"], value_name="v1"
    )
    v2 = v2.melt(
        ignore_index=True, var_name="phase", id_vars=["id", "name"], value_name="v2"
    )
    v = pd.merge(v1, v2, on=["id", "name", "phase"])
    v["diff"] = v["v1"] - v["v2"]
    # fig = px.line(v, x="id", y="diff", facet_col="phase")
    fig = px.bar(
        v,
        x="name",
        y="diff",
        color="phase",
        barmode="group",
    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
    fig.for_each_xaxis(lambda a: a.update(title="Bus Name"))
    return fig


def plot_power_flows(
    p: pd.DataFrame,
    q: pd.DataFrame,
    t: int = None,
) -> go.Figure:
    """
    Plot the active and reactive power flowing into each bus on each phase.

    Parameters
    ----------
    p : pd.DataFrame
        Active power flows with columns ``fb``, ``tb``, ``from_name``,
        ``to_name``, optionally ``t``, and phase columns ``a``, ``b``, ``c``
        (and optionally ``s1``, ``s2`` for triplex lines) containing real floats.
    q : pd.DataFrame
        Reactive power flows with the same structure as ``p``.
    t : int or None
        Time step to plot. If None and flows contain multiple time steps,
        creates an animated figure with a slider.

    Returns
    -------
    fig : Plotly figure object
    """
    p = _remove_empty_triplex_phases(p)
    q = _remove_empty_triplex_phases(q)

    # Check if we should create animation
    animate = t is None and "t" in p.columns and len(p.t.unique()) > 1

    if not animate:
        p = _choose_t(p, t)
        q = _choose_t(q, t)

    id_vars = ["fb", "tb", "from_name", "to_name"]
    phase_cols = [c for c in ["a", "b", "c", "s1", "s2"] if c in p.columns]

    animation_frame = None
    if animate:
        id_vars = ["fb", "tb", "from_name", "to_name", "t"]
        animation_frame = "t"

    p_long = p[id_vars + phase_cols].melt(
        id_vars=id_vars, var_name="phase", value_name="power"
    )
    p_long["part"] = "p"

    q_long = q[id_vars + phase_cols].melt(
        id_vars=id_vars, var_name="phase", value_name="power"
    )
    q_long["part"] = "q"

    df = pd.concat([p_long, q_long], ignore_index=True)

    fig = px.bar(
        df,
        x="to_name",
        y="power",
        facet_col="phase",
        facet_row="part",
        color="phase",
        category_orders={"phase": phase_cols, "part": ["q", "p"]},
        labels={"to_name": "To-Bus Name"},
        animation_frame=animation_frame,
    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))

    # In plotly, facet_row places the first category on the BOTTOM row.
    # With category_orders={"part": ["q", "p"]}, bottom row = q, top row = p.
    # yaxis1..N correspond to the bottom row (q); yaxis(N+1)..2N to top row (p).
    n_phases = len(phase_cols)
    p_first_axis = n_phases + 1  # first p-row yaxis index
    layout_updates = {
        "yaxis_title": "Reactive Power (p.u.)",
        f"yaxis{p_first_axis}_title": "Active Power (p.u.)",
    }
    fig.update_layout(**layout_updates)
    return fig


# def plot_power_flows(s: pd.DataFrame, t=None) -> go.Figure:
#     """
#     Plot the active and reactive power flowing into each bus on each phase.
#     Parameters
#     ----------
#     s : pd.DataFrame
#     t : int or None
#         Time step to plot. Defaults to 0 when a ``t`` column is present.

#     Returns
#     -------
#     fig : Plotly figure object
#     """
#     s = _choose_t(s, t)
#     s = s.melt(
#         ignore_index=True,
#         id_vars=["fb", "tb", "from_name", "to_name"],
#         var_name="phase",
#         value_name="s",
#     )
#     s["p"] = s.s.apply(lambda x: x.real)
#     s["q"] = s.s.apply(lambda x: x.imag)
#     del s["s"]
#     s = s.melt(
#         ignore_index=True,
#         id_vars=["fb", "tb", "from_name", "to_name", "phase"],
#         var_name="part",
#         value_name="power",
#     )
#     fig = px.bar(
#         s,
#         x="to_name",
#         y="power",
#         facet_col="phase",
#         facet_row="part",
#         color="phase",
#         labels={"to_name": "To-Bus Name"},
#     )
#     fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
#     fig.update_layout(
#         yaxis4_title="Active Power (p.u.)",
#         yaxis_title="Reactive Power (p.u.)",
#     )
#     return fig


def plot_gens(p_gens: pd.DataFrame, q_gens: pd.DataFrame, t=None) -> go.Figure:
    """
    Plot the active and reactive power flowing into each bus on each phase.
    Parameters
    ----------
    p_gens : pd.DataFrame
    q_gens : pd.DataFrame
    t : int or None
        Time step to plot. If None and gens contain multiple time steps,
        creates an animated figure with a slider.
    Returns
    -------
    fig : Plotly figure object
    """
    p_gens = _remove_empty_triplex_phases(p_gens)
    q_gens = _remove_empty_triplex_phases(q_gens)

    p_gens = p_gens.copy()
    q_gens = q_gens.copy()

    # Check if we should create animation
    animate = t is None and "t" in p_gens.columns and len(p_gens.t.unique()) > 1

    if not animate:
        p_gens = _choose_t(p_gens, t=t)
        q_gens = _choose_t(q_gens, t=t)

    animation_frame = None
    id_vars_p = ["id", "name"]
    id_vars_gens = ["id", "name", "phase"]
    if animate:
        id_vars_p = ["id", "name", "t"]
        id_vars_gens = ["id", "name", "phase", "t"]
        animation_frame = "t"

    p_gens = p_gens.melt(
        ignore_index=True,
        id_vars=id_vars_p,
        var_name="phase",
        value_name="P",
    )
    q_gens = q_gens.melt(
        ignore_index=True,
        id_vars=id_vars_p,
        var_name="phase",
        value_name="Q",
    )
    gens = pd.merge(
        p_gens,
        q_gens,
        how="outer",
        on=["id", "name", "phase"] + (["t"] if animate else []),
    )
    gens.id = p_gens.id
    gens.name = p_gens.name
    gens.phase = p_gens.phase
    if animate:
        gens["t"] = p_gens["t"]
    gens["P"] = p_gens["P"]
    gens["Q"] = q_gens["Q"]
    gens = gens.melt(
        ignore_index=False,
        id_vars=id_vars_gens,
        var_name="part",
        value_name="power",
    )
    fig = px.bar(
        gens,
        x="name",
        y="power",
        facet_col="phase",
        facet_row="part",
        color="phase",
        labels={"name": "Bus Name"},
        animation_frame=animation_frame,
    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
    fig.update_yaxes(title_text="Active Power (p.u.)", row=2, col=1)
    fig.update_yaxes(title_text="Reactive Power (p.u.)", row=1, col=1)
    return fig


def plot_pq(p: pd.DataFrame, q: pd.DataFrame, t=None) -> go.Figure:
    """
    Plot the active and reactive power.
    Parameters
    ----------
    p : pd.DataFrame
    q : pd.DataFrame
    t : int or None
        Time step to plot. If None and power contain multiple time steps,
        creates an animated figure with a slider.
    Returns
    -------
    fig : Plotly figure object
    """
    p = _remove_empty_triplex_phases(p)
    q = _remove_empty_triplex_phases(q)

    p = p.copy()
    q = q.copy()

    # Check if we should create animation
    animate = t is None and "t" in p.columns and len(p.t.unique()) > 1

    if not animate:
        if t is None:
            t = 0
        if "t" in p.columns:
            t1 = t
            if t is None and len(p) > 0:
                t1 = min(p.t)
            p = pd.DataFrame(p.loc[p.t == t1, :])
            p = p.drop("t", axis=1)
        if "t" in q.columns:
            t2 = t
            if t is None and len(q) > 0:
                t2 = min(q.t)
            q = pd.DataFrame(q.loc[q.t == t2, :])
            q = q.drop("t", axis=1)

    id_col, name_col = _get_id_name_cols(p)
    keep = [id_col, name_col] + [c for c in ("a", "b", "c") if c in p.columns]
    p = p[keep]
    q = q[[id_col, name_col] + [c for c in ("a", "b", "c") if c in q.columns]]

    animation_frame = None
    id_vars = [id_col, name_col]
    id_vars_final = [id_col, name_col, "phase"]
    if animate:
        id_vars = [id_col, name_col, "t"]
        id_vars_final = [id_col, name_col, "phase", "t"]
        animation_frame = "t"

    p = p.melt(
        ignore_index=True,
        id_vars=id_vars,
        var_name="phase",
        value_name="P",
    )
    q = q.melt(
        ignore_index=True,
        id_vars=id_vars,
        var_name="phase",
        value_name="Q",
    )
    merge_cols = [id_col, name_col, "phase"] + (["t"] if animate else [])
    pq = pd.merge(p, q, how="outer", on=merge_cols)
    pq[id_col] = p[id_col]
    pq[name_col] = p[name_col]
    pq.phase = p.phase
    if animate:
        pq["t"] = p["t"]
    pq["P"] = p["P"]
    pq["Q"] = q["Q"]
    pq = pq.melt(
        ignore_index=False,
        id_vars=id_vars_final,
        var_name="part",
        value_name="power",
    )
    fig = px.bar(
        pq,
        x=name_col,
        y="power",
        facet_col="phase",
        facet_row="part",
        color="phase",
        labels={name_col: "Bus Name"},
        animation_frame=animation_frame,
    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
    fig.update_layout(
        yaxis4_title="Active Power (p.u.)",
        yaxis_title="Reactive Power (p.u.)",
    )
    return fig


def compare_flows(s1: pd.DataFrame, s2: pd.DataFrame) -> go.Figure:
    """
    Similar to plot_power_flows but plots two results side by side.
    Parameters
    ----------
    s1 : pd.DataFrame
    s2 : pd.DataFrame

    Returns
    -------
    fig : Plotly figure object
    """
    s1 = _remove_empty_triplex_phases(s1)
    s2 = _remove_empty_triplex_phases(s2)
    s1 = s1.copy()
    s2 = s2.copy()
    if "from_name" not in s1.columns:
        s1["from_name"] = s1.fb
    if "to_name" not in s1.columns:
        s1["to_name"] = s1.tb
    if "from_name" not in s2.columns:
        s2["from_name"] = s2.fb
    if "to_name" not in s2.columns:
        s2["to_name"] = s2.tb

    s1 = s1.melt(
        ignore_index=True,
        id_vars=["fb", "tb", "from_name", "to_name"],
        var_name="phase",
        value_name="s",
    )
    s1["p"] = s1.s.apply(np.real)
    s1["q"] = s1.s.apply(np.imag)
    del s1["s"]
    s1 = s1.melt(
        ignore_index=True,
        id_vars=["fb", "tb", "from_name", "to_name", "phase"],
        var_name="part",
        value_name="s1",
    )
    s2 = s2.melt(
        ignore_index=True,
        id_vars=["fb", "tb", "from_name", "to_name"],
        var_name="phase",
        value_name="s",
    )
    s2["p"] = s2.s.apply(np.real)
    s2["q"] = s2.s.apply(np.imag)
    del s2["s"]
    s2 = s2.melt(
        ignore_index=True,
        id_vars=["fb", "tb", "from_name", "to_name", "phase"],
        var_name="part",
        value_name="s2",
    )
    s = pd.merge(
        s1, s2, on=["fb", "tb", "from_name", "to_name", "phase", "part"], how="outer"
    )
    fig = px.bar(
        s,
        x="to_name",
        y=["s1", "s2"],
        facet_col="phase",
        facet_row="part",
        barmode="group",
        labels={"to_name": "To-Bus Name"},
    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1].upper()))
    fig.update_layout(
        yaxis4_title="Active Power (p.u.)",
        yaxis_title="Reactive Power (p.u.)",
    )
    return fig


def plot_ders(ders: pd.DataFrame) -> go.Figure:
    """
    Plot the generated power for each DER.
    Parameters
    ----------
    ders : pd.DataFrame

    Returns
    -------
    fig : Plotly figure object
    """
    ders = ders.copy()
    dec_var = ders.melt(
        ignore_index=False,
        var_name="phase",
        value_name="Generated Power (p.u.)",
        id_vars=["id", "name"],
    )
    fig = px.bar(
        dec_var,
        x=dec_var.name,
        y="Generated Power (p.u.)",
        color="phase",
        barmode="group",
        labels={"name": "DER Bus Name"},
    )
    fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]).upper())
    return fig


def plot_polar(p: pd.DataFrame, q: pd.DataFrame, t=None) -> go.Figure:
    p = _remove_empty_triplex_phases(p)
    q = _remove_empty_triplex_phases(q)

    p = p.copy()
    q = q.copy()

    # Check if we should create animation
    animate = t is None and "t" in p.columns and len(p.t.unique()) > 1

    if not animate:
        if t is None:
            t = 0
        if "t" in p.columns:
            t1 = t
            if t is None and len(p) > 0:
                t1 = min(p.t)
            p = pd.DataFrame(p.loc[p.t == t1, :])
            p = p.drop("t", axis=1)
        if "t" in q.columns:
            t2 = t
            if t is None and len(q) > 0:
                t2 = min(q.t)
            q = pd.DataFrame(q.loc[q.t == t2, :])
            q = q.drop("t", axis=1)

    id_col, name_col = _get_id_name_cols(p)
    keep = [id_col, name_col] + [c for c in ("a", "b", "c") if c in p.columns]
    p = p[keep]
    q = q[[id_col, name_col] + [c for c in ("a", "b", "c") if c in q.columns]]

    animation_frame = None
    id_vars = [id_col, name_col]
    merge_cols = [id_col, name_col, "phase"]
    if animate:
        id_vars = [id_col, name_col, "t"]
        merge_cols = [id_col, name_col, "phase", "t"]
        animation_frame = "t"

    p = p.melt(
        ignore_index=True,
        id_vars=id_vars,
        var_name="phase",
        value_name="value",
    )
    q = q.melt(
        ignore_index=True,
        id_vars=id_vars,
        var_name="phase",
        value_name="value",
    )
    pq = pd.merge(p, q, how="outer", on=merge_cols)
    pq[id_col] = p[id_col]
    pq[name_col] = p[name_col]
    pq.phase = p.phase
    if animate:
        pq["t"] = p["t"]
    pq["p"] = p.value
    pq["q"] = q.value
    pq["s"] = pq.p.astype(float) + 1j * pq.q.astype(float)
    pq["r"] = np.abs(pq.s)
    pq["th"] = np.angle(pq.s, deg=True)
    fig = px.scatter_polar(
        pq,
        r="r",
        theta="th",
        color="phase",
        # range_theta=[-90, 90],
        start_angle=0,
        direction="counterclockwise",
        hover_data=name_col,
        animation_frame=animation_frame,
    )
    return fig


def plot_batteries(p: pd.DataFrame, soc: pd.DataFrame) -> go.Figure:
    df = p.copy()
    p_last = df.loc[df.t == df.t.max(), :].copy()
    p_last.loc[:, "t"] = df.t.max() + 1
    df = pd.concat([df, p_last]).reset_index(drop=True)
    soc = soc.copy()
    soc.t = soc.t + 1
    soc.value = soc.value * 100
    df["value"] = df.a + df.b + df.c
    df["variable"] = "power"
    df.drop(["a", "b", "c"], axis=1)
    soc["variable"] = "soc"
    df = pd.concat([df, soc])
    fig = px.line(
        df,
        x="t",
        y="value",
        facet_row="variable",
        color="name",
        labels={"name": "Bus Name"},
    )
    for trace in fig.data:
        if trace.yaxis == "y2":  # Top row uses y2 axis
            trace.update(line_shape="hv")
    fig.for_each_annotation(lambda a: a.update(text=""))
    fig.update_layout(
        yaxis2_title="Discharging Power (p.u.)",
        yaxis_title="SOC (%)",
        yaxis=dict(matches=None),  # Make bottom y-axis independent
        yaxis2=dict(matches=None),  # Make top y-axis independent
    )

    return fig


def calculate_nodal_distances(case):
    """
    Calculate the distance (number of hops) from each bus to the source (swing) bus.

    Parameters
    ----------
    case : Case
        Case object containing network data

    Returns
    -------
    dict
        Dictionary mapping bus id to distance from source bus
    """
    from collections import deque

    # Find swing bus
    swing_buses = case.bus_data[case.bus_data.bus_type == "SWING"]
    source_bus = swing_buses.at[swing_buses.index[0], "id"]

    # Build adjacency list
    adjacency = {}
    for idx, branch in case.branch_data.iterrows():
        fb = int(branch["fb"])
        tb = int(branch["tb"])

        if fb not in adjacency:
            adjacency[fb] = []
        if tb not in adjacency:
            adjacency[tb] = []

        adjacency[fb].append(tb)
        adjacency[tb].append(fb)

    # BFS to find distances from source bus
    distances = {source_bus: 0}
    queue = deque([source_bus])

    while queue:
        node = queue.popleft()
        for neighbor in adjacency.get(node, []):
            if neighbor not in distances:
                distances[neighbor] = distances[node] + 1
                queue.append(neighbor)

    return distances


def plot_voltage_vs_distance(
    case,
    v_data,
    title="Voltage vs Distance from Source",
    color_by="algorithm",
    include_secondary_phases=False,
):
    """
    Plot voltage on y-axis vs nodal distance from source bus on x-axis.
    Lines follow the actual network topology (from-bus to to-bus connections).

    Parameters
    ----------
    case : Case
        Case object to calculate distances and branch data
    v_data : pd.DataFrame
        Voltage dataframe with columns: id, name, algorithm, phase, value
    title : str
        Plot title
    color_by : str
        Column name to use for color grouping (e.g., "algorithm")
    include_secondary_phases : bool, optional
        If True, include secondary phases (s1, s2) in the plot. Default is False.

    Returns
    -------
    plotly.graph_objects.Figure
        The plotly figure
    """

    distances = calculate_nodal_distances(case)

    # Add distance column to voltage data
    v_data_copy = v_data.copy()
    v_data_copy["distance"] = v_data_copy["id"].map(distances)

    # Create subplots for each phase
    phases = ["a", "b", "c"]
    if include_secondary_phases:
        phases.extend(["s1", "s2"])

    fig = make_subplots(
        rows=1,
        cols=len(phases),
        subplot_titles=[f"Phase {p.upper()}" for p in phases],
        shared_yaxes=True,
    )

    # Get unique values for color_by column and assign colors automatically
    color_groups = v_data_copy[color_by].unique()
    colors = px.colors.qualitative.Plotly
    if len(color_groups) > len(colors):
        colors = px.colors.qualitative.Alphabet
    color_map = {group: colors[i % len(colors)] for i, group in enumerate(color_groups)}

    # Track which groups have been added to legend to avoid duplicates
    legend_added = set()

    # For each phase, group, and branch, draw a line following the network topology
    for col_idx, phase in enumerate(phases, 1):
        for group in color_groups:
            # Get voltage data for this group and phase
            v_group = v_data_copy[
                (v_data_copy[color_by] == group) & (v_data_copy["phase"] == phase)
            ].copy()

            # Create a mapping of bus id to voltage, name, distance
            v_map = dict(zip(v_group["id"], v_group["value"]))
            d_map = dict(zip(v_group["id"], v_group["distance"]))
            name_map = dict(zip(v_group["id"], v_group["name"]))

            # For each branch, draw a line segment following the topology
            for idx, branch in case.branch_data.iterrows():
                fb = int(branch["fb"])
                tb = int(branch["tb"])

                if fb in v_map and tb in v_map:
                    # Create hover text for both endpoints
                    hover_text = [
                        f"<b>{name_map[fb]}</b><br>ID: {fb}<br>Voltage: {v_map[fb]:.4f} pu<br><b>{color_by}:</b> {group}",
                        f"<b>{name_map[tb]}</b><br>ID: {tb}<br>Voltage: {v_map[tb]:.4f} pu<br><b>{color_by}:</b> {group}",
                    ]

                    # Determine if this group should show in legend
                    show_legend = group not in legend_added
                    if show_legend:
                        legend_added.add(group)

                    # Draw line from from-bus to to-bus
                    fig.add_trace(
                        go.Scatter(
                            x=[d_map[fb], d_map[tb]],
                            y=[v_map[fb], v_map[tb]],
                            mode="lines+markers",
                            name=str(group),
                            line=dict(color=color_map[group], width=1),
                            legendgroup=str(group),
                            showlegend=show_legend,
                            marker=dict(size=4, color=color_map[group]),
                            hovertext=hover_text,
                            hoverinfo="text",
                        ),
                        row=1,
                        col=col_idx,
                    )

    for col_idx in range(1, len(phases) + 1):
        fig.update_xaxes(
            title_text="Distance from Source Bus (hops)", row=1, col=col_idx
        )
    fig.update_yaxes(title_text="Voltage (pu)", row=1, col=1)
    fig.update_layout(title_text=title, hovermode="closest")

    return fig


def plot_line_flow_vs_distance(
    case,
    flow_data,
    flow_name="Power Flow",
    title="Line Flow vs Distance from Source",
    color_by="algorithm",
    include_secondary_phases=False,
):
    """
    Plot line flow on y-axis vs nodal distance from source bus on x-axis.
    Each point represents the flow into the to-bus, plotted at the to-bus distance.
    Lines connect from-bus to to-bus following network topology.
    Hover text shows from-bus and to-bus information.
    Parameters
    ----------
    case : Case
        Case object to calculate distances and branch data
    flow_data : pd.DataFrame
        Line flow dataframe with columns: fb, from_name, tb, to_name, algorithm, phase, value
    flow_name : str
        Name of the flow type for hover text (e.g., "Active Power", "Reactive Power")
    title : str
        Plot title
    color_by : str
        Column name to use for color grouping (e.g., "algorithm", "phase", or any other column)
    include_secondary_phases : bool, optional
        If True, include secondary phases (s1, s2) in the plot. Default is False.
    Returns
    -------
    plotly.graph_objects.Figure
        The plotly figure
    """

    distances = calculate_nodal_distances(case)

    # Add distance columns for both buses
    flow_data_copy = flow_data.copy()
    flow_data_copy["from_distance"] = flow_data_copy["fb"].astype(int).map(distances)
    flow_data_copy["to_distance"] = flow_data_copy["tb"].astype(int).map(distances)

    # Create subplots for each phase
    phases = ["a", "b", "c"]
    if include_secondary_phases:
        phases.extend(["s1", "s2"])

    fig = make_subplots(
        rows=1,
        cols=len(phases),
        subplot_titles=[f"Phase {p.upper()}" for p in phases],
        shared_yaxes=True,
    )

    # Get unique values for color_by column and assign colors automatically
    color_groups = flow_data_copy[color_by].unique()
    colors = px.colors.qualitative.Plotly  # Default plotly color sequence
    if len(color_groups) > len(colors):
        # Use a larger color palette if needed
        colors = px.colors.qualitative.Alphabet
    color_map = {group: colors[i % len(colors)] for i, group in enumerate(color_groups)}

    # Track which groups have been added to legend to avoid duplicates
    legend_added = set()

    # For each phase, color group, and branch, draw a line following the network topology
    for col_idx, phase in enumerate(phases, 1):
        for group in color_groups:
            # Get flow data for this group and phase
            flow_group = flow_data_copy[
                (flow_data_copy[color_by] == group) & (flow_data_copy["phase"] == phase)
            ].copy()

            if len(flow_group) == 0:
                continue

            # Create mappings from branch (fb, tb) to flow data
            branch_flow = {}  # (fb, tb) -> flow value for that branch
            dist_map = {}  # bus_id -> distance
            name_map = {}  # bus_id -> name

            for idx, row in flow_group.iterrows():
                fb = int(row["fb"])
                tb = int(row["tb"])
                branch_flow[(fb, tb)] = row["value"]
                dist_map[fb] = row["from_distance"]
                dist_map[tb] = row["to_distance"]
                name_map[fb] = row["from_name"]
                name_map[tb] = row["to_name"]

            # For each branch, draw a line segment from from-bus to to-bus
            for idx, branch in case.branch_data.iterrows():
                fb = int(branch["fb"])
                tb = int(branch["tb"])

                # Check if we have flow data for this branch
                if (fb, tb) not in branch_flow:
                    continue

                # Get the flow value for this specific branch
                current_flow = branch_flow[(fb, tb)]

                # Skip if flow is NaN
                if np.isnan(current_flow):
                    continue

                # Get the flow value for the upstream branch (where fb is the to-bus)
                upstream_flow = None
                for (upstream_fb, upstream_tb), flow_val in branch_flow.items():
                    if upstream_tb == fb and not np.isnan(flow_val):
                        upstream_flow = flow_val
                        break

                fb_dist = dist_map.get(fb)
                tb_dist = dist_map.get(tb)

                if fb_dist is None or tb_dist is None:
                    continue

                # Determine if this group should show in legend
                show_legend = group not in legend_added
                if show_legend:
                    legend_added.add(group)

                # Create hover text for this branch
                branch_hover = (
                    f"<b>From:</b> {name_map.get(fb, fb)} (ID: {fb})<br>"
                    f"<b>To:</b> {name_map.get(tb, tb)} (ID: {tb})<br>"
                    f"<b>{flow_name}:</b> {current_flow:.4f}<br>"
                    f"<b>{color_by}:</b> {group}"
                )

                # If from-bus has no upstream flow (source bus), only plot the to-bus point
                if upstream_flow is None:
                    fig.add_trace(
                        go.Scatter(
                            x=[tb_dist],
                            y=[current_flow],
                            mode="markers",
                            name=str(group),
                            line=dict(color=color_map[group], width=1),
                            legendgroup=str(group),
                            showlegend=show_legend,
                            marker=dict(size=4, color=color_map[group]),
                            hovertext=[branch_hover],
                            hoverinfo="text",
                        ),
                        row=1,
                        col=col_idx,
                    )
                else:
                    # Find the upstream branch info for hover text
                    upstream_hover = None
                    for (upstream_fb, upstream_tb), flow_val in branch_flow.items():
                        if upstream_tb == fb and not np.isnan(flow_val):
                            upstream_hover = (
                                f"<b>From:</b> {name_map.get(upstream_fb, upstream_fb)} (ID: {upstream_fb})<br>"
                                f"<b>To:</b> {name_map.get(upstream_tb, upstream_tb)} (ID: {upstream_tb})<br>"
                                f"<b>{flow_name}:</b> {flow_val:.4f}<br>"
                                f"<b>{color_by}:</b> {group}"
                            )
                            break

                    if upstream_hover is None:
                        upstream_hover = branch_hover

                    # Draw line from from-bus to to-bus
                    fig.add_trace(
                        go.Scatter(
                            x=[fb_dist, tb_dist],
                            y=[upstream_flow, current_flow],
                            mode="lines+markers",
                            name=str(group),
                            line=dict(color=color_map[group], width=1),
                            legendgroup=str(group),
                            showlegend=show_legend,
                            marker=dict(size=4, color=color_map[group]),
                            hovertext=[upstream_hover, branch_hover],
                            hoverinfo="text",
                        ),
                        row=1,
                        col=col_idx,
                    )

    for col_idx in range(1, len(phases) + 1):
        fig.update_xaxes(
            title_text="Distance from Source Bus (hops)", row=1, col=col_idx
        )
    fig.update_yaxes(
        title_text=f"{flow_name} (kW)" if "Power" in flow_name else f"{flow_name}",
        row=1,
        col=1,
    )
    fig.update_layout(title_text=title, hovermode="closest")

    return fig


def plot_network(
    model: LinDistBase | Case,
    result: Optional[PowerFlowResult] = None,
    v: Optional[pd.DataFrame] = None,
    s: Optional[pd.DataFrame] = None,
    p_flow: Optional[pd.DataFrame] = None,
    q_flow: Optional[pd.DataFrame] = None,
    p_gen: Optional[pd.DataFrame] = None,
    q_gen: Optional[pd.DataFrame] = None,
    p_bat: Optional[pd.DataFrame] = None,
    soc: Optional[pd.DataFrame] = None,
    v_min: float = 0.95,
    v_max: float = 1.05,
    show_phases: str = "abc",
    show_reactive_power: bool = False,
    t: Optional[int] = None,
) -> go.Figure:
    """
    Plot the distribution network showing voltage and power results.
    Parameters
    ----------
    model : LinDistBase
    result: PowerFlowResult, (default=None) result of solver containing all results. Overrides other dataframe arguments.
    v : pd.DataFrame, (default=None) Dataframe containing voltage magnitudes for each bus.
    s : pd.DataFrame, (default=None) Dataframe containing power flows for each branch. Either s or p_flow and q_flow should be provided.
    p_flow : pd.DataFrame, (default=None) Dataframe containing power flows for each branch.
    q_flow : pd.DataFrame, (default=None) Dataframe containing power flows for each branch.
    p_gen : pd.DataFrame, (default=None) Dataframe containing actve power generated by each generator.
    q_gen : pd.DataFrame, (default=None) Dataframe containing reactive power generated by each generator.
    p_bat : pd.DataFrame, (default=None) Dataframe containing actve power generated by each battery.
    soc : pd.DataFrame, (default=None) Dataframe containing fractional state of charge of each battery.
    v_min : (default=0.95) Used for scaling node colors.
    v_max : (default=1.05) Used for scaling node colors.
    show_phases : (default="abc") valid options: "a", "b", "c", or "abc"
    show_reactive_power : (default=False) If True, show reactive power flows instead of active power flows.

    Returns
    -------
    fig: plotly.graph_objects.Figure
    """
    if result is not None:
        # Extract data from result
        v = result.voltages
        p_flow = result.active_power_flows
        q_flow = result.reactive_power_flows
        p_gen = result.active_power_generation
        q_gen = result.reactive_power_generation
        p_bat = result.battery_active_power
        soc = result.soc

    # Remove empty triplex phases
    if v is not None:
        v = _remove_empty_triplex_phases(v)
    if s is not None:
        s = _remove_empty_triplex_phases(s)
    if p_flow is not None:
        p_flow = _remove_empty_triplex_phases(p_flow)
    if q_flow is not None:
        q_flow = _remove_empty_triplex_phases(q_flow)
    if p_gen is not None:
        p_gen = _remove_empty_triplex_phases(p_gen)
    if q_gen is not None:
        q_gen = _remove_empty_triplex_phases(q_gen)
    if p_bat is not None:
        p_bat = _remove_empty_triplex_phases(p_bat)

    # validate phases
    if show_phases.lower() not in ["a", "b", "c", "abc"]:
        raise ValueError("Invalid phase. Must be 'a', 'b', 'c', or 'abc'.")
    show_phases = show_phases.lower()
    phase_list = sorted([ph.lower() for ph in show_phases])
    bus_data = model.bus_data.copy()
    branch_data = model.branch_data.copy()
    gen_data = model.gen_data.copy()
    cap_data = model.cap_data.copy()
    bat_data = (
        model.bat_data.copy()
        if hasattr(model, "bat_data") and model.bat_data is not None
        else None
    )

    node_size = 10
    edge_scale = 20
    edge_min = 1

    # Compute global max power flow magnitude for consistent line thickness across frames
    _phase_cols = [
        c
        for c in ["a", "b", "c", "s1", "s2"]
        if p_flow is not None and c in p_flow.columns
    ]
    _global_p_max = (
        float(p_flow[_phase_cols].fillna(0).sum(axis=1).abs().max())
        if _phase_cols
        else None
    )
    _phase_cols_q = [
        c
        for c in ["a", "b", "c", "s1", "s2"]
        if q_flow is not None and c in q_flow.columns
    ]
    _global_q_max = (
        float(q_flow[_phase_cols_q].fillna(0).sum(axis=1).abs().max())
        if _phase_cols_q
        else None
    )

    # --- original static processing (unchanged) ---
    bus_data = _process_bus_data(bus_data, v, phase_list, t)
    branch_data = _process_branch_data(
        branch_data,
        bus_data,
        s,
        p_flow,
        q_flow,
        phase_list,
        edge_scale,
        edge_min,
        t,
        p_max=_global_p_max,
        q_max=_global_q_max,
    )
    gen_data = _process_gen_data(gen_data, p_gen, q_gen, t)
    bat_data = _process_bat_data(bat_data, p_bat, soc, t)

    node_trace = _make_node_trace(bus_data, node_size, v_max, v_min)
    cap_trace, gen_trace, bat_trace, substation_trace = _make_asset_markers(
        bus_data, cap_data, gen_data, bat_data, node_size
    )
    edge_traces = _make_edge_traces(branch_data, show_phases, show_reactive_power)
    reverse_flow_markers_trace = _make_reverse_flow_marker_trace(
        branch_data, node_size, show_reactive_power
    )
    node_trace.text = _make_hover_text(
        branch_data, bus_data, cap_data, gen_data, bat_data
    )
    title = _make_title(show_phases, show_reactive_power)

    fig = go.Figure(
        data=[
            *edge_traces,
            substation_trace,
            reverse_flow_markers_trace,
            bat_trace,
            cap_trace,
            gen_trace,
            node_trace,
        ]
    )

    # --- animation (only when t is not explicitly given and multiple steps exist) ---
    animation_times = _get_animation_times(
        v, s, p_flow, q_flow, p_gen, q_gen, p_bat, soc
    )
    if t is None and len(animation_times) > 1:
        bat_data_raw = (
            model.bat_data.copy()
            if hasattr(model, "bat_data") and model.bat_data is not None
            else None
        )
        frames = []
        for t_step in animation_times:
            _bd = _process_bus_data(model.bus_data.copy(), v, phase_list, t_step)
            _brd = _process_branch_data(
                model.branch_data.copy(),
                _bd,
                s,
                p_flow,
                q_flow,
                phase_list,
                edge_scale,
                edge_min,
                t_step,
                p_max=_global_p_max,
                q_max=_global_q_max,
            )
            _gd = _process_gen_data(model.gen_data.copy(), p_gen, q_gen, t_step)
            _btd = _process_bat_data(
                bat_data_raw.copy() if bat_data_raw is not None else None,
                p_bat,
                soc,
                t_step,
            )
            _nt = _make_node_trace(_bd, node_size, v_max, v_min)
            _ct, _gt, _btt, _st = _make_asset_markers(
                _bd, cap_data, _gd, _btd, node_size
            )
            _ets = _make_edge_traces(_brd, show_phases, show_reactive_power)
            _rfmt = _make_reverse_flow_marker_trace(
                _brd, node_size, show_reactive_power
            )
            _nt.text = _make_hover_text(_brd, _bd, cap_data, _gd, _btd)
            frames.append(
                go.Frame(
                    data=[*_ets, _st, _rfmt, _btt, _ct, _gt, _nt],
                    name=str(t_step),
                )
            )
        fig.frames = frames
        fig.update_layout(
            sliders=[
                {
                    "active": 0,
                    "x": 0.1,
                    "y": -0.05,
                    "len": 0.8,
                    "steps": [
                        {
                            "label": str(ts),
                            "method": "animate",
                            "args": [
                                [str(ts)],
                                {
                                    "mode": "immediate",
                                    "frame": {"duration": 0, "redraw": True},
                                    "transition": {"duration": 0},
                                },
                            ],
                        }
                        for ts in animation_times
                    ],
                }
            ],
        )

    fig.update_layout(
        title=title,
        plot_bgcolor="White",
        paper_bgcolor="White",
        title_font_color="Black",
        legend_font_color="Black",
        legend_bgcolor="White",
        margin=dict(t=50, b=10, l=10, r=10),
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
        legend=dict(x=0.8, y=0.9),
        font=dict(family="Droid Sans Mono", color="Black"),
        # annotations=arrow_list[0:1],
    )

    return fig


def _get_animation_times(*dfs) -> list:
    """Return sorted unique integer time steps from the first dataframe with a 't' column."""
    for df in dfs:
        if df is not None and isinstance(df, pd.DataFrame) and "t" in df.columns:
            try:
                times = sorted(int(v) for v in df["t"].dropna().unique())
                if len(times) > 1:
                    return times
            except (TypeError, ValueError):
                pass
    return []


def _process_bus_data(bus_data, v, phase_list, t):
    _v = None
    if v is not None:
        _v = _choose_t(v.copy(), t)
    bus_data["y"] = bus_data.latitude - bus_data.latitude.mean()
    bus_data["x"] = bus_data.longitude - bus_data.longitude.mean()
    bus_data["color"] = "white"
    if bus_data.x.abs().max() > 0:
        bus_data.x = bus_data.x / bus_data.x.abs().max()
    if bus_data.y.abs().max() > 0:
        bus_data.y = bus_data.y / bus_data.y.abs().max()
    if _v is not None:
        _v.index = _v.id - 1
        bus_data.v_a = _v.a if "a" in _v.columns else np.nan
        bus_data.v_b = _v.b if "b" in _v.columns else np.nan
        bus_data.v_c = _v.c if "c" in _v.columns else np.nan
        bus_data["v_s1"] = _v["s1"] if "s1" in _v.columns else np.nan
        bus_data["v_s2"] = _v["s2"] if "s2" in _v.columns else np.nan
        available_phases = [p for p in phase_list + ["s1", "s2"] if p in _v.columns]
        bus_data.color = _v[available_phases].mean(axis=1)
    return bus_data


def _process_branch_data(
    branch_data,
    bus_data,
    s,
    p_flow,
    q_flow,
    phase_list,
    edge_scale,
    edge_min,
    t,
    p_max=None,
    q_max=None,
):
    _s = None
    if s is not None:
        _s = _choose_t(s.copy(), t)
    if s is None and p_flow is not None and q_flow is not None:
        from_bus_map = {
            int(tb): int(fb) for fb, tb in branch_data.loc[:, ["fb", "tb"]].to_numpy()
        }
        _s = p_flow.copy()
        cols_to_drop = [c for c in ["a", "b", "c", "s1", "s2"] if c in _s.columns]
        _s = _s.drop(cols_to_drop, axis=1)
        for ph in ["a", "b", "c", "s1", "s2"]:
            if ph in p_flow.columns:
                _s[ph] = p_flow[ph] + 1j * q_flow[ph]
        if "tb" not in _s.columns:
            _s["tb"] = _s["id"]
        if "fb" not in _s.columns:
            _s["fb"] = _s["tb"].map(from_bus_map)
        _s = _choose_t(_s, t)

    branch_data = branch_data.loc[branch_data.status != "OPEN", :]
    branch_data.index = branch_data.tb.to_numpy() - 1
    branch_data["s_a"] = complex(np.nan, np.nan)
    branch_data["s_b"] = complex(np.nan, np.nan)
    branch_data["s_c"] = complex(np.nan, np.nan)
    branch_data["s_s1"] = complex(np.nan, np.nan)
    branch_data["s_s2"] = complex(np.nan, np.nan)
    branch_data["p_abs"] = 1
    branch_data["q_abs"] = 1
    branch_data["p_norm"] = edge_min
    branch_data["q_norm"] = edge_min
    branch_data["p_direction"] = 1
    branch_data["q_direction"] = 1
    branch_data["x0"] = bus_data.loc[branch_data.fb.to_numpy() - 1].x.to_numpy()
    branch_data["x1"] = bus_data.loc[branch_data.tb.to_numpy() - 1].x.to_numpy()
    branch_data["y0"] = bus_data.loc[branch_data.fb.to_numpy() - 1].y.to_numpy()
    branch_data["y1"] = bus_data.loc[branch_data.tb.to_numpy() - 1].y.to_numpy()
    branch_data["x_mid"] = 1 / 2 * (branch_data.x0 + branch_data.x1)
    branch_data["y_mid"] = 1 / 2 * (branch_data.y0 + branch_data.y1)
    if _s is not None:
        # _s.index = _s.tb.to_numpy() - 1
        # Save the original index so we can restore it at the end
        _orig_index = branch_data.index

        # Use (fb, tb) as a unique key on both sides
        _s = _s.set_index(pd.MultiIndex.from_arrays([_s.fb.to_numpy(), _s.tb.to_numpy()]))
        branch_data = branch_data.set_index(
            pd.MultiIndex.from_arrays([branch_data.fb.to_numpy(), branch_data.tb.to_numpy()])
        )

        branch_data["s_a"] = _s.a if "a" in _s.columns else complex(np.nan, np.nan)
        branch_data["s_b"] = _s.b if "b" in _s.columns else complex(np.nan, np.nan)
        branch_data["s_c"] = _s.c if "c" in _s.columns else complex(np.nan, np.nan)
        branch_data["s_s1"] = (
            _s["s1"] if "s1" in _s.columns else complex(np.nan, np.nan)
        )
        branch_data["s_s2"] = (
            _s["s2"] if "s2" in _s.columns else complex(np.nan, np.nan)
        )
        available_phases = [p for p in phase_list + ["s1", "s2"] if p in _s.columns]
        p_complex = _s.loc[:, available_phases].sum(axis=1)
        branch_data["p_abs"] = p_complex.map(lambda z: abs(z.real))
        branch_data["q_abs"] = p_complex.map(lambda z: abs(z.imag))
        branch_data["p_direction"] = p_complex.map(lambda z: np.sign(z.real + 1e-6))
        branch_data["q_direction"] = p_complex.map(lambda z: np.sign(z.imag + 1e-6))
        _p_denom = p_max if p_max is not None else branch_data["p_abs"].max()
        _q_denom = q_max if q_max is not None else branch_data["q_abs"].max()
        branch_data["p_norm"] = (
            branch_data["p_abs"].to_numpy() / _p_denom * edge_scale + edge_min
            if _p_denom > 0
            else branch_data["p_norm"]
        )
        branch_data["q_norm"] = (
            branch_data["q_abs"].to_numpy() / _q_denom * edge_scale + edge_min
            if _q_denom > 0
            else branch_data["q_norm"]
        )

        # Restore the original index so downstream code (which likely uses tb-1) still works
        branch_data.index = _orig_index
    return branch_data


def _process_gen_data(gen_data, p_gen, q_gen, t):
    """Merge generator setpoints from result frames into gen_data.

    Supports multiple phase column formats:
    - Traditional 3-phase: columns a/b/c
    - Split-phase (triplex): columns s1/s2
    - Normalized: columns with phase/value
    """

    if p_gen is not None and p_gen.shape[0] == 0:
        p_gen = None
    if q_gen is not None and q_gen.shape[0] == 0:
        q_gen = None

    if p_gen is not None:
        p_gen = _choose_t(p_gen, t)
    if q_gen is not None:
        q_gen = _choose_t(q_gen, t)

    gen_data.index = gen_data.id.to_numpy() - 1

    def _latest_abc(df):
        if df is None:
            return None
        # If time-series, take the last time step for plotting
        if "t" in df.columns:
            df = df.sort_values(["id", "t"]).groupby("id", as_index=False).tail(1)
        df.index = df.id.to_numpy() - 1
        return df

    p_gen = _latest_abc(p_gen)
    q_gen = _latest_abc(q_gen)

    def _assign_phase_values(gen_data, phase_data, p_or_q, phase_cols):
        """Assign phase power values, handling missing phases gracefully."""
        if phase_data is None:
            return gen_data

        for phase in phase_cols:
            col_name = f"{p_or_q}_{phase}"
            if col_name in gen_data.columns:
                # If phase column exists in phase_data, use it; otherwise use NaN
                if phase in phase_data.columns:
                    try:
                        gen_data[col_name] = phase_data[phase].to_numpy()
                    except (KeyError, ValueError):
                        pass
        return gen_data

    # Determine which phase columns are present in gen_data
    phase_cols_3ph = ["a", "b", "c"]
    phase_cols_split = ["s1", "s2"]

    # Get phase columns that actually exist in gen_data
    p_phase_cols = [
        ph for ph in phase_cols_3ph + phase_cols_split if f"p_{ph}" in gen_data.columns
    ]
    q_phase_cols = [
        ph for ph in phase_cols_3ph + phase_cols_split if f"q_{ph}" in gen_data.columns
    ]

    # Assign values for each phase, skipping if they don't exist in phase_data
    gen_data = _assign_phase_values(gen_data, p_gen, "p", p_phase_cols)
    gen_data = _assign_phase_values(gen_data, q_gen, "q", q_phase_cols)

    return gen_data


def _process_bat_data(bat_data, battery_active_power, soc, t):
    """Merge battery results from PowerFlowResult if available.

    Supports multiple phase column formats (a/b/c, s1/s2, or phase/value normalized).
    """
    # Return early if any required data is None or empty
    if (
        bat_data is None
        or bat_data.shape[0] == 0
        or battery_active_power is None
        or battery_active_power.shape[0] == 0
        or soc is None
        or soc.shape[0] == 0
    ):
        return bat_data

    p_bat = _choose_t(battery_active_power.copy(), t)
    soc_data = _choose_t(soc.copy(), t)

    # Skip processing if DataFrames are empty after time filtering
    if p_bat.shape[0] == 0 or soc_data.shape[0] == 0:
        return bat_data

    # Determine available phase columns
    phase_cols = []
    if "a" in p_bat.columns and "b" in p_bat.columns and "c" in p_bat.columns:
        phase_cols = ["a", "b", "c"]
    elif "s1" in p_bat.columns and "s2" in p_bat.columns:
        phase_cols = ["s1", "s2"]
    else:
        # Normalized format (phase/value) - skip, not supported for plotting yet
        return bat_data

    # Rename power columns with _p suffix before merge to ensure consistency
    try:
        p_bat_renamed = p_bat[["id"] + phase_cols].rename(
            columns={ph: f"{ph}_p" for ph in phase_cols}
        )

        # Merge power data
        bat_data = bat_data.merge(p_bat_renamed, on="id", how="left")

        # Sum multi-phase power
        p_cols = [f"{ph}_p" for ph in phase_cols]
        if all(col in bat_data.columns for col in p_cols):
            bat_data["p"] = bat_data[p_cols].sum(axis=1)
    except (KeyError, ValueError):
        # If column selection fails, skip power merging
        pass

    # Merge SOC data
    try:
        bat_data = bat_data.merge(soc_data[["id", "value"]], on="id", how="left")
        if "value" in bat_data.columns:
            bat_data["soc"] = bat_data["value"]
    except (KeyError, ValueError):
        # If SOC merge fails, skip it
        pass

    return bat_data


def _make_reverse_flow_marker_trace(branch_data, node_size, show_reactive_power):
    if show_reactive_power:
        reverse_list_x = branch_data.loc[
            branch_data.q_direction < 0, "x_mid"
        ].to_numpy()
        reverse_list_y = branch_data.loc[
            branch_data.q_direction < 0, "y_mid"
        ].to_numpy()
    else:
        reverse_list_x = branch_data.loc[
            branch_data.p_direction < 0, "x_mid"
        ].to_numpy()
        reverse_list_y = branch_data.loc[
            branch_data.p_direction < 0, "y_mid"
        ].to_numpy()
    reverse_flow_markers_trace = go.Scatter()
    if not show_reactive_power:
        reverse_flow_markers_trace = go.Scatter(
            x=reverse_list_x,
            y=reverse_list_y,
            mode="markers",
            marker=dict(
                symbol="star-triangle-up",
                size=node_size * 1,
                color="orange",
                line_width=0.5,
                line_color="black",
            ),
            showlegend=True,
            name="Reverse Power Flow",
            hoverinfo="none",
        )
    return reverse_flow_markers_trace


def _make_edge_traces(branch_data, show_phases, show_reactive_power):
    edge_traces = []
    for _, edge in branch_data.iterrows():
        x0, x1 = edge.x0, edge.x1
        y0, y1 = edge.y0, edge.y1
        dash = "solid"
        linewidth = edge.p_norm
        direction = edge.p_direction
        if show_reactive_power:
            linewidth = edge.q_norm
            direction = edge.q_direction
        if (
            show_phases.lower() != "abc"
            and show_phases.lower() not in edge.phases.lower()
        ):
            dash = "dot"
        # if edge.type == "switch":
        #     dash = "dash"
        color = "darkblue"
        if direction < 0:
            color = "maroon"
        edge_trace = go.Scatter(
            x=[x0, x1],
            y=[y0, y1],
            mode="lines",
            line=dict(color=color, width=linewidth, dash=dash),
            showlegend=False,
            hoverinfo="none",
        )
        edge_traces.append(edge_trace)
    return edge_traces


def _make_hover_text(branch_data, bus_data, cap_data, gen_data, bat_data=None):
    text = []
    for i, bus_row in enumerate(bus_data.itertuples()):
        raw_phases = bus_row.phases.lower()

        # Determine which phases to display for this bus
        is_triplex = "s1" in raw_phases or "s2" in raw_phases
        if is_triplex:
            active_phases = [p for p in ["s1", "s2"] if p in raw_phases]
            primary = str(getattr(bus_row, "primary_phase", "") or "").strip().upper()
            phase_labels = {
                p: f"{primary}-{p.upper()}" if primary else p.upper()
                for p in active_phases
            }
        else:
            active_phases = [p for p in ["a", "b", "c"] if p in raw_phases]
            phase_labels = {p: p.upper() for p in active_phases}

        def _fmt(val, phase):
            """Format a numeric value; show dashes if phase not active."""
            if phase not in active_phases:
                return "  ---  "
            try:
                return f"{float(val):>7.3f}"
            except (TypeError, ValueError):
                return "  NaN  "

        def _row(icon, label, vals_by_phase):
            parts = " ".join(
                _fmt(vals_by_phase.get(p, np.nan), p) for p in active_phases
            )
            return f"{icon} {label:<8} {parts}<br>"

        # Header
        header_labels = "   ".join(f"{phase_labels[p]:>5}" for p in active_phases)
        hover_text = f"<b>  Bus: {bus_row.name:<5}        (p.u.)</b><br>"
        hover_text += f"<b>               {header_labels}</b><br>"

        # Voltages
        if is_triplex:
            v_vals = {
                "s1": getattr(bus_row, "v_s1", np.nan),
                "s2": getattr(bus_row, "v_s2", np.nan),
            }
        else:
            v_vals = {"a": bus_row.v_a, "b": bus_row.v_b, "c": bus_row.v_c}
        hover_text += _row("⚡", "V Mag", v_vals)

        # Loads
        if is_triplex:
            pl_vals = {
                "s1": getattr(bus_row, "pl_s1", np.nan),
                "s2": getattr(bus_row, "pl_s2", np.nan),
            }
            ql_vals = {
                "s1": getattr(bus_row, "ql_s1", np.nan),
                "s2": getattr(bus_row, "ql_s2", np.nan),
            }
        else:
            pl_vals = {"a": bus_row.pl_a, "b": bus_row.pl_b, "c": bus_row.pl_c}
            ql_vals = {"a": bus_row.ql_a, "b": bus_row.ql_b, "c": bus_row.ql_c}
        hover_text += _row("💡", "P Load", pl_vals)
        hover_text += _row("💡", "Q Load", ql_vals)

        # Capacitor (abc buses only)
        if (
            not is_triplex
            and cap_data is not None
            and bus_row.id in cap_data.id.to_numpy()
        ):
            q_cap = cap_data.loc[
                cap_data.id == bus_row.id, ["q_a", "q_b", "q_c"]
            ].to_numpy()[0]
            hover_text += _row(
                "🔃", "Q Cap", {"a": q_cap[0], "b": q_cap[1], "c": q_cap[2]}
            )

        # Generator
        if bus_row.id in gen_data.id.to_numpy():
            gen_row = gen_data.loc[gen_data.id == bus_row.id].iloc[0]
            if is_triplex:
                pg_vals = {
                    "s1": gen_row.get("p_s1", np.nan),
                    "s2": gen_row.get("p_s2", np.nan),
                }
                qg_vals = {
                    "s1": gen_row.get("q_s1", np.nan),
                    "s2": gen_row.get("q_s2", np.nan),
                }
            else:
                pg_vals = {
                    "a": gen_row.get("p_a", np.nan),
                    "b": gen_row.get("p_b", np.nan),
                    "c": gen_row.get("p_c", np.nan),
                }
                qg_vals = {
                    "a": gen_row.get("q_a", np.nan),
                    "b": gen_row.get("q_b", np.nan),
                    "c": gen_row.get("q_c", np.nan),
                }
            hover_text += _row("⚙️", "P Gen", pg_vals)
            hover_text += _row("⚙️", "Q Gen", qg_vals)

        # Battery
        if (
            bat_data is not None
            and len(bat_data) > 0
            and bus_row.id in bat_data.id.to_numpy()
        ):
            bat_row = bat_data.loc[bat_data.id == bus_row.id].iloc[0]
            if is_triplex:
                pb_vals = {
                    "s1": bat_row.get("s1_p", bat_row.get("p_s1", 0.0)),
                    "s2": bat_row.get("s2_p", bat_row.get("p_s2", 0.0)),
                }
            else:
                pb_vals = {
                    "a": bat_row.get("a_p", bat_row.get("p_a", 0.0)),
                    "b": bat_row.get("b_p", bat_row.get("p_b", 0.0)),
                    "c": bat_row.get("c_p", bat_row.get("p_c", 0.0)),
                }
            soc_val = bat_row.get("soc", 0.0)
            hover_text += _row("🔋", "P Bat", pb_vals)
            hover_text += f"   SOC     {soc_val * 100:>7.1f}%<br>"

        # Branch flow
        edge = branch_data.loc[branch_data.tb == bus_row.id, :]
        if len(edge) > 0:
            fb = edge.fb.to_numpy()[0]
            from_name = bus_data.loc[bus_data.id == fb, "name"].to_numpy()[0]
            if is_triplex:
                ss1 = (
                    edge.s_s1.to_numpy()[0]
                    if "s_s1" in edge.columns
                    else complex(np.nan, np.nan)
                )
                ss2 = (
                    edge.s_s2.to_numpy()[0]
                    if "s_s2" in edge.columns
                    else complex(np.nan, np.nan)
                )
                pflow_vals = {"s1": np.real(ss1), "s2": np.real(ss2)}
                qflow_vals = {"s1": np.imag(ss1), "s2": np.imag(ss2)}
            else:
                sa = edge.s_a.to_numpy()[0]
                sb = edge.s_b.to_numpy()[0]
                sc = edge.s_c.to_numpy()[0]
                pflow_vals = {"a": np.real(sa), "b": np.real(sb), "c": np.real(sc)}
                qflow_vals = {"a": np.imag(sa), "b": np.imag(sb), "c": np.imag(sc)}
            hover_text += "<br>"
            hover_text += (
                f"<b>  {edge.type.to_numpy()[0]}: {from_name} → {bus_row.name}</b><br>"
            )
            hover_text += _row("➡️", "P Flow", pflow_vals)
            hover_text += _row("➡️", "Q Flow", qflow_vals)

        text.append(hover_text)
    return text


def _make_title(show_phases, show_reactive_power):
    title = "<b>Network Plot (P.U.)</b>"
    # if _v is not None:
    title = title + "<br>Node color: "
    if show_phases == "abc":
        title = title + "Average voltage magnitude"
    else:
        title = title + f"Phase-{show_phases.upper()} voltage magnitude"
    # if _s is not None:
    title = title + "<br>Line width:"
    if show_phases == "abc":
        title = title + " Total"
    else:
        title = title + f" Phase-{show_phases.upper()}"
    if show_reactive_power:
        title = title + " <i>reactive</i> power flow"
    else:
        title = title + " <i>active</i> power flow"
    title = title + " (reverse flow in red)."
    return title


def _make_asset_markers(bus_data, cap_data, gen_data, bat_data, node_size):
    # Add substation marker
    substation_buses = bus_data.loc[bus_data.bus_type == "SWING", :]
    substation_trace = go.Scatter(
        x=substation_buses["x"],
        y=substation_buses["y"],
        mode="markers",
        marker=dict(
            symbol="square",
            size=node_size * 2,
            color="black",
            line_width=1,
            line_color="black",
        ),
        showlegend=True,
        name="Substation",
        hoverinfo="none",
    )
    # Add generator markers
    gen_buses = bus_data.loc[bus_data.id.isin(gen_data.id), :]
    gen_trace = go.Scatter(
        x=gen_buses["x"],
        y=gen_buses["y"],
        mode="markers",
        marker=dict(
            symbol="circle",
            size=node_size * 2,
            color="white",
            line_width=1,
            line_color="black",
        ),
        showlegend=True,
        name="Generators",
        hoverinfo="none",
    )
    # Add battery markers
    if bat_data is not None and len(bat_data) > 0:
        bat_buses = bus_data.loc[bus_data.id.isin(bat_data.id), :]
        bat_trace = go.Scatter(
            x=bat_buses["x"],
            y=bat_buses["y"],
            mode="markers",
            marker=dict(
                symbol="square",
                size=node_size * 2,
                color="lightblue",
                line_width=1,
                line_color="black",
            ),
            showlegend=True,
            name="Batteries",
            hoverinfo="none",
        )
    else:
        bat_trace = go.Scatter(
            x=[],
            y=[],
            mode="markers",
            showlegend=False,
            hoverinfo="none",
        )
    # Add capacitor markers
    cap_buses = bus_data.loc[bus_data.id.isin(cap_data.id), :]
    cap_trace = go.Scatter(
        x=cap_buses["x"],
        y=cap_buses["y"],
        mode="markers",
        marker=dict(
            symbol="star-diamond",
            size=node_size * 2,
            color="white",
            line_width=1,
            line_color="black",
        ),
        showlegend=True,
        name="Capacitors",
        hoverinfo="none",
    )
    return cap_trace, gen_trace, bat_trace, substation_trace


def _make_node_trace(bus_data, node_size, v_max, v_min):
    node_trace = go.Scatter(
        x=bus_data["x"],
        y=bus_data["y"],
        mode="markers",
        marker=dict(
            showscale=True,
            cmin=v_min,
            cmax=v_max,
            # colorscale options
            # 'Greys' | 'YlGnBu' | 'Greens' | 'YlOrRd' | 'Bluered' | 'RdBu' |
            # 'Reds' | 'Blues' | 'Picnic' | 'Rainbow' | 'Portland' | 'Jet' |
            # 'Hot' | 'Blackbody' | 'Earth' | 'Electric' | 'Viridis' | 'Aggrnyl'
            colorscale="Viridis",
            reversescale=False,
            size=node_size,
            color=bus_data.color,
            line_width=node_size / 5,
            line_color="black",
        ),
        showlegend=False,
        text=bus_data["name"],
        hovertemplate="%{text}",
        hoverlabel=dict(font=dict(family="Monospace")),
        textposition="top center",
    )
    return node_trace
